services:
  postgres:
    image: pgvector/pgvector:pg16
    container_name: talkbook-postgres
    environment:
      POSTGRES_DB: talkbook
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - talkbook_pg_data:/var/lib/postgresql/data

    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d talkbook"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  talkbook_pg_data: